version: "3"
services:
  python_app:
    image: python:latest
    container_name: my_python_app_name
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./volumes/app_env:/app_env
      - ./volumes/app:/app
      - /etc/localtime:/etc/localtime:ro
    command: /bin/bash -c "source /app_env/bin/activate && python -u script.py"
