version: "3"
services:
  python_app:
    image: python:latest
    container_name: python_app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./volumes/app_env:/usr/local/lib//app_env
      - ./volumes/app:/app
      - /etc/localtime:/etc/localtime:ro
    command: /bin/bash -c "source /usr/local/lib//app_env/bin/activate && python -u script.py"